modLoader="javafml"
loaderVersion="[43,)"
license="MIT License https://github.com/romelo333/notenoughwands1.8.8/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/romelo333/notenoughwands1.8.8/issues"
displayURL="http://github.com/romelo333/notenoughwands1.8.8/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty, romelo333"

[[mods]]
modId="notenoughwands"
version="${file.jarVersion}"
displayName="Not Enough Wands"
#updateJSONURL="http://myurl.me/" #optional
description='''
You can never have enough wands!
'''
[[dependencies.notenoughwands]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.notenoughwands]]
    modId="mcjtylib"
    mandatory=false
    versionRange="[1.19-7.2.6,)"
    ordering="AFTER"
    side="BOTH"
