modLoader="javafml"
loaderVersion="[2,)"
license="MIT License https://github.com/romelo333/notenoughwands1.8.8/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/romelo333/notenoughwands1.8.8/issues"
displayURL="http://github.com/romelo333/notenoughwands1.8.8/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty, romelo333"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="notenoughwands"
version="${file.jarVersion}"
displayName="Not Enough Wands"
#updateJSONURL="http://myurl.me/" #optional
description='''
You can never have enough wands!
'''
[[dependencies.notenoughwands]]
modId="neoforge"
type="required"
versionRange="[21.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.notenoughwands]]
    modId="mcjtylib"
    mandatory=false
    versionRange="[1.21-9.0.2,)"
    ordering="AFTER"
    side="BOTH"
